### ISSUE TITLE
Allow latest 2.0 vips version

### ISSUE THREAD

**Issue by mstaack** [osiemsiedem/intervention-image-vips-driver#22]
https://github.com/libvips/php-vips/tags

2.0 uses ffi, so no need to use/install ext-vips anymore ! 🎉

**Comment by mstaack** [comment]
@bonzai what do you think?

**Comment by bonzai** [comment]
Sorry for the late answer.

I'll take a look on Saturday or Sunday.

**Comment by bonzai** [comment]
I'll release a new version this week.

**Comment by mstaack** [comment]
hey @bonzai have you had time to look at this?

cheers max

**Comment by bonzai** [comment]
A little late, but I've tagged a new release with the changes.

If something doesn't work, please let me know.
