### ISSUE TITLE
Not resizing

### ISSUE THREAD

**Issue by jarodium** [osiemsiedem/intervention-image-vips-driver#4]
Taking a 450x305 colored png and resizing it to 150x150 it does not appear to be working.
The output image is saving properly but there are no differences in the image.

```php
$manager = new Intervention\Image\ImageManager(array('driver' => 'vips'));
$imm = $manager->make("minibus1.png");
$fdim = [150,150];
$imm->resize($fdim[0], $fdim[1], function ($constraint) {
        //Constraint the current aspect-ratio if the image. As a shortcut to proportional resizing you can use widen() or heighten().
        //$constraint->aspectRatio();
        //Keep image from being upsized.
        //$constraint->upsize();
})->save("output.png");

$imm->destroy();
```
The constraints are commented out purprose, but it still does not resize when they are uncommented. Perhaps it's due to resizecanvas not supported?

**Comment by bonzai** [comment]
It works for me.

```
$ composer require intervention/image
$ composer require osiemsiedem/intervention-image-vips-driver
```

```php
require 'vendor/autoload.php';

use Intervention\Image\ImageManager;

(new ImageManager(array('driver' => 'vips')))
    ->make('in.png')
    ->resize(150, 150)
    ->save('out.png');
```

| Input (in.png) | Output (out.png) |
| --- | --- |
| ![](https://user-images.githubusercontent.com/98191/63596854-77721700-c5bc-11e9-8123-8a690241ccfe.png) | ![](https://user-images.githubusercontent.com/98191/63596860-79d47100-c5bc-11e9-82ce-339f27841465.png) |

Can you share the `minibus1.png` image?

**Comment by jarodium** [comment]
Hello

Which version of libvips are you currently using? The image is attached

![minibus1](https://user-images.githubusercontent.com/1470446/63676374-b8e40b80-c7e2-11e9-8232-d12e5fd38674.png)

**Comment by bonzai** [comment]
| # | Headers | Library | ABI |
|----|---------|---------|---------|
| 1. | 8.7.4 | 8.8.1 | 53.0.11 |
| 2. | 8.9.0 | 8.9.0 | 54.0.12 |

Your libvips is too old.

Please upgrade to a newer version, and if the problem persists, let me know.
